# Generated by Django 4.2.2 on 2023-06-08 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product_category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pcid", models.IntegerField()),
                ("Pcname", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Pid", models.IntegerField()),
                ("Pname", models.CharField(max_length=100)),
                ("Pprice", models.IntegerField()),
                ("Pdescription", models.TextField()),
                ("Pdate", models.DateField()),
                (
                    "Pcname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="app.product_category",
                    ),
                ),
            ],
        ),
    ]
